turtlebot4_node:
  ros__parameters:
    wifi:
      interface: "wlan0"

    # Setting power_saver to True will make the TurtleBot 4
    # disable the camera and lidar while docked
    power_saver: True  

    # Supported Functions:
    # Dock
    # Undock
    # Wall Follow Left
    # Wall Follow Right
    # Power
    # EStop
    # RPLIDAR Stop
    # RPLIDAR Start
    # OAKD Stop
    # OAKD Start

    # Menu Functions:
    # Scroll Up
    # Scroll Down
    # Back
    # Select
    # Help

    # Buttons:
    # create3_1
    # create3_power
    # create3_2
    # hmi_1
    # hmi_2
    # hmi_3
    # hmi_4

    # Format:
    # button: ["SHORT_PRESS_FUNC", "LONG_PRESS_FUNC", "LONG_PRESS_DURATION_MS"]

    buttons:  
      create3_1: ["Dock", "Wall Follow Left", "2000"]
      create3_power: ["EStop", "Power", "3000"]
      create3_2: ["Undock", "Wall Follow Right", "2000"]

      hmi_1: ["Select"]
      hmi_2: ["Back"]
      hmi_3: ["Scroll Up"]
      hmi_4: ["Scroll Down"]

      # Menu entry must match a function
    menu:
      entries: ["Dock", "Undock", "EStop", "Wall Follow Left", "Wall Follow Right", "Power", "Help"]

    # Controller button functions
    # Buttons:
    # a b x y
    # up down left right
    # l1 l2 l3 r1 r2 r3
    # share options home

    controller:
      a: ["Select"]
      b: ["EStop"]
      x: ["Back"]
      up: ["Scroll Up"]
      down: ["Scroll Down"]
      l2: ["Wall Follow Left"]
      r2: ["Wall Follow Right"]
      home: ["Dock", "Undock", "3000"]

turtlebot4_base_node:
  ros__parameters:
    # GPIO definition for HMI. Do NOT change if you are using the standard PCBA.
    gpio:
      user_button_1: 19
      user_button_2: 16
      user_button_3: 26
      user_button_4: 20

      led_green_power: 17
      led_green_motors: 18
      led_green_comms: 27
      led_green_wifi: 24
      led_green_battery: 22
      led_red_battery: 23
      led_green_user_1: 25
      led_green_user_2: 6
      led_red_user_2: 21

      display_reset: 13
