name: turtlebot4_robot_ci

on: [push, pull_request]

jobs:
  turtlebot4_jazzy_ci:
    name: Jazzy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
          use-ros2-testing: true
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          import-token: ${{ secrets.GITHUB_TOKEN }}
          vcs-repo-file-url: dependencies.repos
          package-name:
            turtlebot4_bringup
            turtlebot4_diagnostics
            turtlebot4_base
            turtlebot4_tests
